language: shell

os:
  - linux
#  - osx
  - windows
osx_image: xcode10.1

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: out
  repo: tdlight-team/tdlib-docs
  on:
    branch: master

script: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    bash travis/linux.sh; 
  fi
  
#  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
#    bash travis/mac.sh; 
#  fi
  
  if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
    bash travis/win.sh; 
  fi 
