language: shell

os:
  - linux
  - windows
osx_image: xcode10.1

arch:
  - amd64
  - arm64

cache:
  bundler: true
  cocoapods: true
  ccache: true
  directories:
    - ".autoconf"
    - "$HOME/.m2"
    - "$HOME/.cache"
  
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: out
    repo: tdlight-team/tdlib-docs
    on:
        branch: master
#  - provider: script
#    skip-cleanup: true
#    script: "mvn -B -V deploy"
#before_install:
#  - cp .travis.settings.xml $HOME/.m2/settings.xml

script: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    ./travis/linux.sh; 
  fi
  
  if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
    ./travis/win.sh; 
  fi
  ./travis/deploy_master.sh

