language: shell

os:
  - linux
  - windows
arch:
  - amd64
  - arm64
osx_image: xcode10.1
dist: bionic
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - while travis_wait 50 sleep 300 &> /tmp/build.log || (tail -n 100 /tmp/build.log && exit 1); do echo "=====[ $SECONDS seconds, buildroot still building... ]====="; done
addons:
  apt:
    update: true
    packages:
    - make
    - git
    - zlib1g-dev
    - libssl-dev
    - gperf
    - php
    - cmake
    - g++
    - ccache
    - maven
    - openjdk-11-jdk
    - python3
cache:
  bundler: true
  cocoapods: true
  ccache: true
  directories:
    - ".autoconf"
    - "$HOME/.m2"
    - "$HOME/.ccache"
  
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: out/docs
    repo: tdlight-team/tdlib-docs
    target_branch: master
    email: andrea@cavallium.it
    name: "Andrea Cavalli"
    verbose: true
#  - provider: script
#    skip-cleanup: true
#    script: "mvn -B -V deploy"

install: travis/install_dependencies.sh
script: travis_wait 30 travis/build.sh
after_success: travis/build_success.sh
