language: shell

os:
  - linux
  - windows
arch:
  - amd64
  - arm64
osx_image: xcode10.1
dist: bionic
before_install:
  - sudo apt-get -y install make git zlib1g-dev libssl-dev gperf php cmake openjdk-11-jdk-headless g++ ccache maven
addons:
  apt:
    update: true
cache:
  bundler: true
  cocoapods: true
  ccache: true
  directories:
    - ".autoconf"
    - "$HOME/.m2"
    - "$HOME/.cache"
  
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: out
    repo: tdlight-team/tdlib-docs
    on:
        branch: master
#  - provider: script
#    skip-cleanup: true
#    script: "mvn -B -V deploy"
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script: |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    bash -e travis/linux.sh; 
    bash -e travis/deploy_master.sh
  fi
  
  if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
    bash travis/win.sh;
    bash travis/deploy_master.sh
  fi

